name: Build LLM Indexes

on:
  push:
    branches: [ main, master ]
    paths-ignore:
      - ".github/**"
  pull_request:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-indexes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Generate llms indexes
        run: node scripts/build-llms-index.mjs

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: auto-update llms indexes [skip ci]"
          file_pattern: |
            llms.txt
            llms-full.txt
